/* Student AI open learning bank. CEFR levels derived from CEFR-J/Open Language Profiles. */
(function(){
  'use strict';
  const bilingual = [
    ['ability','قدرة','A2','noun'],['accept','يقبل','A2','verb'],['achieve','يحقق','A2','verb'],['action','فعل / إجراء','A1','noun'],['activity','نشاط','A1','noun'],['address','عنوان','A1','noun'],['advice','نصيحة','A2','noun'],['afraid','خائف','A1','adjective'],['agree','يوافق','A1','verb'],['air','هواء','A2','noun'],
    ['always','دائمًا','A1','adverb'],['answer','إجابة','A1','noun'],['appear','يظهر','A2','verb'],['arrive','يصل','A1','verb'],['ask','يسأل','A1','verb'],['beautiful','جميل','A1','adjective'],['because','لأن','A1','conjunction'],['become','يصبح','A2','verb'],['before','قبل','A1','preposition'],['begin','يبدأ','A1','verb'],
    ['believe','يعتقد','A2','verb'],['book','كتاب','A1','noun'],['bring','يجلب','A2','verb'],['build','يبني','A2','verb'],['business','عمل / تجارة','A2','noun'],['buy','يشتري','A1','verb'],['change','يغيّر','A1','verb'],['choose','يختار','A2','verb'],['class','صف','A1','noun'],['clean','نظيف','A1','adjective'],
    ['close','يغلق','A1','verb'],['come','يأتي','A1','verb'],['computer','حاسوب','A1','noun'],['continue','يستمر','A2','verb'],['country','بلد','A1','noun'],['create','ينشئ','A2','verb'],['day','يوم','A1','noun'],['decide','يقرر','A2','verb'],['different','مختلف','A1','adjective'],['difficult','صعب','A1','adjective'],
    ['education','تعليم','A2','noun'],['enjoy','يستمتع','A1','verb'],['example','مثال','A1','noun'],['experience','خبرة / تجربة','A2','noun'],['family','عائلة','A1','noun'],['feel','يشعر','A1','verb'],['find','يجد','A1','verb'],['finish','ينهي','A1','verb'],['friend','صديق','A1','noun'],['future','مستقبل','A2','noun'],
    ['give','يعطي','A1','verb'],['good','جيد','A1','adjective'],['great','عظيم / رائع','A1','adjective'],['happy','سعيد','A1','adjective'],['have','يمتلك / لديه','A1','verb'],['help','يساعد','A1','verb'],['important','مهم','A1','adjective'],['improve','يحسّن','A2','verb'],['information','معلومات','A1','noun'],['interesting','ممتع / مثير للاهتمام','A1','adjective'],
    ['know','يعرف','A1','verb'],['language','لغة','A1','noun'],['learn','يتعلم','A1','verb'],['leave','يغادر','A1','verb'],['lesson','درس','A1','noun'],['listen','يستمع','A1','verb'],['live','يعيش','A1','verb'],['look','ينظر','A1','verb'],['make','يصنع','A1','verb'],['mean','يعني','A2','verb'],
    ['message','رسالة','A2','noun'],['money','مال','A1','noun'],['need','يحتاج','A1','verb'],['new','جديد','A1','adjective'],['next','التالي','A1','adjective'],['number','رقم','A1','noun'],['open','يفتح','A1','verb'],['people','الناس','A1','noun'],['place','مكان','A1','noun'],['practice','تدريب / ممارسة','A2','noun'],
    ['problem','مشكلة','A1','noun'],['question','سؤال','A1','noun'],['read','يقرأ','A1','verb'],['remember','يتذكر','A1','verb'],['right','صحيح / يمين','A1','adjective'],['school','مدرسة','A1','noun'],['speak','يتحدث','A1','verb'],['student','طالب','A1','noun'],['study','يدرس','A1','verb'],['success','نجاح','A2','noun'],
    ['teacher','مدرس','A1','noun'],['think','يفكر','A1','verb'],['time','وقت','A1','noun'],['today','اليوم','A1','adverb'],['translate','يترجم','A2','verb'],['understand','يفهم','A1','verb'],['university','جامعة','A2','noun'],['use','يستخدم','A1','verb'],['want','يريد','A1','verb'],['word','كلمة','A1','noun'],
    ['work','عمل','A1','noun'],['write','يكتب','A1','verb'],['accurate','دقيق','B1','adjective'],['achievement','إنجاز','B1','noun'],['advantage','ميزة','A2','noun'],['affect','يؤثر','B1','verb'],['allow','يسمح','A2','verb'],['although','على الرغم من','A2','conjunction'],['amount','كمية','B1','noun'],['analyze','يحلل','B1','verb'],
    ['announce','يعلن','B1','verb'],['avoid','يتجنب','B1','verb'],['behavior','سلوك','B1','noun'],['benefit','فائدة','B1','noun'],['challenge','تحدٍ','B1','noun'],['communicate','يتواصل','B1','verb'],['compare','يقارن','B1','verb'],['complete','يكمل','A2','verb'],['condition','حالة / شرط','B1','noun'],['consider','يعتبر / يفكر في','B1','verb'],
    ['develop','يطوّر','A2','verb'],['environment','بيئة','A2','noun'],['explain','يشرح','A2','verb'],['focus','يركز','B1','verb'],['knowledge','معرفة','B1','noun'],['method','طريقة','B1','noun'],['opportunity','فرصة','B1','noun'],['prepare','يستعد / يجهز','A2','verb'],['progress','تقدم','B1','noun'],['require','يتطلب','B1','verb'],
    ['result','نتيجة','A2','noun'],['skill','مهارة','A2','noun'],['solution','حل','B1','noun'],['specific','محدد','B1','adjective'],['support','دعم','B1','noun'],['technology','تكنولوجيا','A2','noun'],['available','متاح','A2','adjective'],['communicate','يتواصل','B1','verb'],['confident','واثق','B1','adjective'],['effective','فعّال','B1','adjective'],
    ['essential','أساسي','B1','adjective'],['evaluate','يقيّم','B2','verb'],['evidence','دليل','B1','noun'],['independent','مستقل','B1','adjective'],['influence','تأثير','B1','noun'],['maintain','يحافظ على','B2','verb'],['participate','يشارك','B1','verb'],['perspective','وجهة نظر','B2','noun'],['relevant','ذو صلة','B2','adjective'],['significant','مهم / ملحوظ','B2','adjective'],
    ['approach','نهج / أسلوب','B2','noun'],['assume','يفترض','B2','verb'],['complex','معقد','B2','adjective'],['consequence','نتيجة / عاقبة','B2','noun'],['demonstrate','يوضح / يبرهن','B2','verb'],['establish','يؤسس','B2','verb'],['interpret','يفسر','B2','verb'],['justify','يبرر','B2','verb'],['reliable','موثوق','B2','adjective'],['strategy','استراتيجية','B2','noun'],
    ['coherent','مترابط','C1','adjective'],['compelling','مقنع','C1','adjective'],['convey','ينقل / يعبّر','C1','verb'],['crucial','حاسم','C1','adjective'],['derive','يستمد','C1','verb'],['elaborate','يفصل / مفصل','C1','verb'],['enhance','يعزز','C1','verb'],['explicit','صريح / واضح','C1','adjective'],['fundamental','جوهري','C1','adjective'],['insight','رؤية عميقة','C1','noun'],
    ['nuance','دقة / فرق بسيط','C1','noun'],['plausible','معقول / محتمل','C1','adjective'],['profound','عميق','C1','adjective'],['substantial','كبير / جوهري','C1','adjective'],['sustain','يحافظ على / يدعم','C1','verb']
  ].map(([word,ar,level,pos])=>({word,ar,level,pos}));

  const irregular = [
    ['be','was/were','been'],['become','became','become'],['begin','began','begun'],['break','broke','broken'],['bring','brought','brought'],['build','built','built'],['buy','bought','bought'],['catch','caught','caught'],['choose','chose','chosen'],['come','came','come'],['cost','cost','cost'],['cut','cut','cut'],['do','did','done'],['draw','drew','drawn'],['drink','drank','drunk'],['drive','drove','driven'],['eat','ate','eaten'],['fall','fell','fallen'],['feel','felt','felt'],['find','found','found'],['fly','flew','flown'],['forget','forgot','forgotten'],['get','got','got/gotten'],['give','gave','given'],['go','went','gone'],['grow','grew','grown'],['have','had','had'],['hear','heard','heard'],['keep','kept','kept'],['know','knew','known'],['leave','left','left'],['lose','lost','lost'],['make','made','made'],['meet','met','met'],['pay','paid','paid'],['put','put','put'],['read','read','read'],['run','ran','run'],['say','said','said'],['see','saw','seen'],['sell','sold','sold'],['send','sent','sent'],['sit','sat','sat'],['sleep','slept','slept'],['speak','spoke','spoken'],['spend','spent','spent'],['stand','stood','stood'],['swim','swam','swum'],['take','took','taken'],['teach','taught','taught'],['tell','told','told'],['think','thought','thought'],['understand','understood','understood'],['wear','wore','worn'],['win','won','won'],['write','wrote','written']
  ].map(([base,past,participle])=>({base,past,participle}));

  const sentences = [
    ['I study English every day.','A1'],['She goes to university by bus.','A1'],['They are playing football now.','A1'],['My teacher explains the lesson clearly.','A1'],['We have a test tomorrow.','A1'],['Please open your book on page ten.','A1'],['I usually drink tea in the morning.','A1'],['He can speak English very well.','A1'],
    ['I have lived here for three years.','A2'],['She was studying when I called her.','A2'],['If it rains, we will stay at home.','A2'],['Learning a language takes regular practice.','A2'],['I would like to improve my pronunciation.','A2'],['The students finished their homework before class.','A2'],['This exercise is easier than the previous one.','A2'],['You should listen carefully to the speaker.','A2'],
    ['Although the exam was difficult, I remained confident.','B1'],['Technology has changed the way students learn.','B1'],['The teacher encouraged us to express our opinions.','B1'],['Regular practice can significantly improve your fluency.','B1'],['I had already completed the task before the deadline.','B1'],['The article provides useful information about education.','B1'],['If I had more time, I would read more English books.','B1'],['Students should evaluate information before accepting it.','B1'],
    ['Despite facing several challenges, she achieved excellent results.','B2'],['The evidence suggests that consistent practice is more effective than occasional study.','B2'],['It is essential to consider different perspectives before reaching a conclusion.','B2'],['The university introduced a strategy to enhance online learning.','B2'],['He explained the concept in a way that everyone could understand.','B2'],['The results were significant enough to change our original approach.','B2'],
    ['A compelling argument should be coherent, relevant, and supported by reliable evidence.','C1'],['The lecturer highlighted a subtle distinction that many students had previously overlooked.','C1'],['Although the proposal appears plausible, its long-term consequences require careful evaluation.','C1'],['Effective communication often depends on understanding nuance as well as literal meaning.','C1']
  ].map(([text,level])=>({text,level}));

  const placement = [
    {l:'A1',s:'grammar',q:'I ___ a student.',o:['am','is','are','be'],a:0},{l:'A1',s:'vocabulary',q:'Choose the opposite of “big”.',o:['small','long','high','fast'],a:0},{l:'A1',s:'grammar',q:'She ___ English every day.',o:['study','studies','studying','studied'],a:1},{l:'A1',s:'vocabulary',q:'“Teacher” means:',o:['مدرس','طالب','كتاب','مدرسة'],a:0},
    {l:'A2',s:'grammar',q:'Yesterday, we ___ to the market.',o:['go','went','gone','going'],a:1},{l:'A2',s:'grammar',q:'This book is ___ than that one.',o:['interesting','more interesting','most interesting','interest'],a:1},{l:'A2',s:'vocabulary',q:'“Improve” is closest to:',o:['make better','make smaller','forget','stop'],a:0},{l:'A2',s:'grammar',q:'I have known him ___ 2022.',o:['for','since','from','at'],a:1},
    {l:'B1',s:'grammar',q:'If I ___ enough money, I would travel.',o:['have','had','will have','having'],a:1},{l:'B1',s:'vocabulary',q:'“Benefit” is closest to:',o:['advantage','problem','question','argument'],a:0},{l:'B1',s:'grammar',q:'By the time I arrived, they ___ dinner.',o:['finish','finished','had finished','have finished'],a:2},{l:'B1',s:'vocabulary',q:'“Confident” means:',o:['sure of yourself','very tired','angry','careless'],a:0},
    {l:'B2',s:'grammar',q:'The report ___ by the committee before publication.',o:['reviewed','was reviewed','has reviewing','review'],a:1},{l:'B2',s:'vocabulary',q:'“Reliable evidence” is evidence that is:',o:['trustworthy','expensive','unusual','brief'],a:0},{l:'B2',s:'grammar',q:'Had I known earlier, I ___ you.',o:['would tell','would have told','told','had told'],a:1},{l:'B2',s:'vocabulary',q:'“Significant” is closest to:',o:['important','ordinary','temporary','hidden'],a:0},
    {l:'A1',s:'listening',q:'استمع ثم اختر الجملة الصحيحة.',audio:'I study English every day.',o:['I study English every day.','I studied English yesterday.','I speak Arabic every day.','I study math every day.'],a:0},
    {l:'A2',s:'listening',q:'استمع ثم اختر الجملة الصحيحة.',audio:'She has lived here for three years.',o:['She lived here three days.','She has lived here for three years.','She will live here for a year.','She is living there now.'],a:1},
    {l:'B1',s:'listening',q:'استمع ثم اختر المعنى الأقرب.',audio:'Regular practice can significantly improve your fluency.',o:['الممارسة المنتظمة تحسن الطلاقة بشكل ملحوظ.','الطلاقة لا تحتاج تدريبًا.','التدريب يقلل من الطلاقة.','الممارسة مهمة للكتابة فقط.'],a:0},
    {l:'B2',s:'listening',q:'استمع ثم اختر الجملة الصحيحة.',audio:'It is essential to consider different perspectives before reaching a conclusion.',o:['يجب تجاهل الآراء المختلفة.','من الضروري دراسة وجهات نظر مختلفة قبل الوصول إلى نتيجة.','النتيجة أهم من الأدلة.','وجهة النظر الواحدة كافية دائمًا.'],a:1},
    {l:'C1',s:'vocabulary',q:'“Plausible” most nearly means:',o:['seemingly reasonable','completely certain','irrelevant','harmful'],a:0},{l:'C1',s:'grammar',q:'Rarely ___ such a convincing presentation.',o:['I have seen','have I seen','I saw','did I have seen'],a:1},{l:'C1',s:'vocabulary',q:'A “nuance” is:',o:['a subtle difference','a major error','a final result','a fixed rule'],a:0},{l:'C1',s:'grammar',q:'The proposal, ___ initially seemed impractical, proved successful.',o:['that','which','what','where'],a:1}
  ];

  window.StudentAIBank = Object.freeze({version:'2.0.0', bilingual, irregular, sentences, placement});
})();
